### ISSUE TITLE
No module named 'discord_downloader'

### ISSUE THREAD

**Issue by iBlz** [bmorcos/discord-downloader#6]
```
Traceback (most recent call last):
  File "/mnt/pve/drive/discord/discord-downloader/discord_downloader/downloader.py", line 6, in <module>
    from discord_downloader.config import cfg
ModuleNotFoundError: No module named 'discord_downloader'
```
Fix your code please!

**Comment by bmorcos** [comment]
Hi there and thanks for taking an interest in my code.

It's usually good practice to provide a bit more detail when filing an issue to help the maintainers track down any problems. At the very least you should include the command you run and a full stack trace and even better is detailed instructions of how to reproduce an error, including your environment, for more complex issues.

In any case, for the problem you are posting it appears as though you don't have the `discord_downloader` package installed. There are instructions of how to install the package in the [Readme](https://github.com/bmorcos/discord-downloader#getting-started). You can check if `discord_downloader` is installed by running `pip freeze | grep discord_downloader` and checking there is an output. More generally, `pip freeze` will show you what packages are installed.

Good luck, I hope you get this working!
