### ISSUE TITLE
cli not working

### ISSUE THREAD

**Issue by fadh1l** [bmorcos/discord-downloader#7]
`    client = discord.Client()
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents' `

any clue on how to fix it?

**Comment by bmorcos** [comment]
Hi there,

This is an old project that I've not been actively maintaining but I did just try it again and realized we need to use `discord<2`. I am not going to upgrade this utility to work with the newer `discord>1` at this time so I added an upper bound for the `discord` requirement so this will work now if you install it.
